
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Postgres2018!
    testWhileIdle: true
    url: jdbc:postgresql://10.0.0.109:5432/fornecedor
    username: postgres
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
